### ISSUE TITLE
Incorrect copyright in license

### ISSUE THREAD

**Issue by gnewton** [AAFC-MBB/reference-data-manager#1]
The license reads:
`Copyright (c) 2018 Biological Informatics CoE @ Agriculture and Agri-Food Canada`

it should read:

`Copyright (c) 2018 Government of Canada`

All AAFC-MBB repos should have this same copyright.

**Comment by ChunfangZheng** [comment]
The license has been corrected. 
The rules for licensing are listed at:
 http://redmine.biodiversity.agr.gc.ca/projects/developper-tools/wiki/Git_Tutorial_and_Best_Practices#Licensing
